name: Runner Test

on:
  workflow_dispatch: 

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Nachricht senden
        run: echo "Hallo von Linux Mint! Der Runner funktioniert!"

      - name: Node Version abfragen
        run: node -v

      - name: Docker Version abfragen
        run: docker --verion
            
