name: Runner Test

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: System-Infos auf der VM abfragen
        run: |
             echo "Hallo von Linux Mint!"
             node -v
             docker --version
